### ISSUE TITLE
CI Chapter - Image getting created in Host machine

### ISSUE THREAD

**Issue by venkatesh-cv** [turnbullpress/dockerbook-code#49]
## Context
 I'm reading the Continuous Integration Chapter and following the Jenkins + Ruby setup. I'm able to launch Jenkins and configure & run the build. However, the build fails. Appreciate your help to understand what is going on.

## Error Description
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

## Debugging attempts
   ` Tagged the imag as 'myapp' to see whats happening. Noticed that the image is actually getting created on the host machine & not inside the jenkins container. I'm not sure if this should the case. Having created a docker server inside Jenkins container, the image should have been created in there. Is suspect that possibly this could be  the a reason for issue described above
  - Tried listing the folder contents at each step to see what the runtime is seeing & did not find anything amiss.
  - and still when the container is started up the error shown above is encountered. [Details below](#JENKINS-OUTPUT)
- My thoughts
  - the unix port binding during startup is confusing

## Container startup script
```
docker run -i -p 8080:8080 -p 50000:50000  -v /var/run/docker.sock:/var/run/docker.sock --name jenkins cvenkatesh/jenkins-docker-server
-- if you are wondering about the missing config folder, its deliberately skipped. I'm planning to get to it later.
```
## Execute Shell Script
```
IMAGE=$(sudo docker build -t myapp . |tail -l |awk '{ print $NF }')
IMAGE=$(sudo docker images myapp -q)
MNT="/var/jenkins_home/jobs/${JOB_NAME}"
ls -l $MNT
ls -l $MNT/workspace
CONTAINER=$(sudo docker run -d -v $MNT:/opt/project -w /opt/project/workspace $IMAGE /bin/bash -c 'cd /opt/project/workspace;rake spec --trace')
sudo docker attach $CONTAINER
RC=$(sudo docker wait $CONTAINER)
sudo docker rm $CONTAINER
exit $RC
```
## JENKINS-OUTPUT
```
+ MNT=/var/jenkins_home/jobs/test_build
+ ls -l /var/jenkins_home/jobs/test_build
total 16
drwxr-xr-x 46 jenkins jenkins 4096 Feb 10 10:54 builds
-rw-r--r--  1 jenkins jenkins 2011 Feb 10 10:54 config.xml
lrwxrwxrwx  1 jenkins jenkins   22 Feb 10 10:54 lastStable -> builds/lastStableBuild
lrwxrwxrwx  1 jenkins jenkins   26 Feb 10 10:54 lastSuccessful -> builds/lastSuccessfulBuild
-rw-r--r--  1 jenkins jenkins    3 Feb 10 10:54 nextBuildNumber
drwxr-xr-x  8 jenkins jenkins 4096 Feb 10 09:37 workspace
+ ls -l /var/jenkins_home/jobs/test_build/workspace
total 52
-rw-r--r-- 1 jenkins jenkins   202 Feb 10 08:57 Dockerfile
-rw-r--r-- 1 jenkins jenkins    61 Feb 10 08:57 Gemfile
-rw-r--r-- 1 jenkins jenkins   418 Feb 10 08:57 Gemfile.lock
-rw-r--r-- 1 jenkins jenkins 10273 Feb 10 08:57 LICENSE
-rw-r--r-- 1 jenkins jenkins   142 Feb 10 08:57 README.md
-rw-r--r-- 1 jenkins jenkins   265 Feb 10 08:57 Rakefile
drwxr-xr-x 2 jenkins jenkins  4096 Feb 10 08:57 centos
drwxr-xr-x 2 jenkins jenkins  4096 Feb 10 08:57 debian
drwxr-xr-x 3 root    root     4096 Feb 10 09:37 opt
drwxr-xr-x 2 jenkins jenkins  4096 Feb 10 08:57 spec
drwxr-xr-x 2 jenkins jenkins  4096 Feb 10 08:57 ubuntu
+ sudo docker run -d -v /var/jenkins_home/jobs/test_build:/opt/project -w /opt/project/workspace e7d8c91df2b0 /bin/bash -c cd /opt/project/workspace;rake spec --trace

+ CONTAINER=476087fc73cafeffed7639332c5cff7541ca89efeb2b3e5f1b168c408c4ebee0
+ sudo docker attach 476087fc73cafeffed7639332c5cff7541ca89efeb2b3e5f1b168c408c4ebee0
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/lib/ruby/vendor_ruby/rake/application.rb:684:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE

```

## Images on the host machine (trimmed list)
```
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
myapp                              latest              998203e99399        6 seconds ago       188MB
cvenkatesh/jenkins-docker-server   latest              1600db4417b8        6 hours ago         1.05GB
cvenkatesh/ubuntu-node-mongo       latest              586d8cfd0062        45 hours ago        562MB
```

**Comment by venkatesh-cv** [comment]
## Ok, I got it to work finally today.
## Here are my observations
- The docker image created by the jenkins job is actually created on the host machine. 
- The container spawned by the job also gets created in the host machine. This can be observed if we comment out the line `#sudo docker rm $CONTAINER` in the shell script in the jenkins job.
- As a result the container gets started in the host machine & not as a child of or inside the jenkins container (as i had imagined it would) . Not sure if this is by design
- Now here is the important piece i discovered. The -v volume mapping to ` -v /var/jenkins_home:/var/jenkins_home` on the jenkins container. The use of the same name to the mapped volume in the container allows us to use the same path `/var/jenkins_home` inside the shell script we add in the jenkins job.  
- Use of a mapped volume & also that the name `/var/jenkins_home` be used exactly as-is is very important because as stated in the first two points, the build-container runs on the host machine & looks for /var/home path. Since the jenkins used the very same as a mapped volume, the files pulled by it would be sitting on the host machine for the build-container to access from and also the path name remains the same for the script to work.
**This was not elucidated in the book and hence my having to rough it out a bit! ** 
I'm jotting it down here hoping that this helps someone.

**Comment by venkatesh-cv** [comment]
I encountered another issue when running the jenkins job multiple times. git had trouble checking out code the second time as it got permission denied on the /spec/report/*.xml folder
- tried different things by adding advanced git behavior such as removing repo & force cloning. Nothing worked. Finally i had to resort to force removing the folder from the host-machine using `rm -rf /var/jenkins_home/jobs/test_build/workspace/spec` folder
- had to run the remove folder each time i ran the build. I'm not interested in debugging this any further. So, I'll be moving along in the book. 
```
Building in workspace /var/jenkins_home/jobs/test_build/workspace
Wiping out workspace first.
java.nio.file.AccessDeniedException: /var/jenkins_home/jobs/test_build/workspace/spec/reports/SPEC-These-are-sample-RSpec-tests.448.xml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at hudson.Util.tryOnceDeleteFile(Util.java:290)
	at hudson.Util.deleteFile(Util.java:245)
Caused: java.io.IOException: Unable to delete '/var/jenkins_home/jobs/test_build/workspace/spec/reports/SPEC-These-are-sample-RSpec-tests.448.xml'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteFile(Util.java:250)
	at hudson.FilePath.deleteRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1220)
	at hudson.FilePath.deleteRecursive(FilePath.java:1202)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1220)
	at hudson.FilePath.deleteRecursive(FilePath.java:1202)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1220)
	at hudson.FilePath.access$1100(FilePath.java:197)
	at hudson.FilePath$15.invoke(FilePath.java:1194)
	at hudson.FilePath$15.invoke(FilePath.java:1191)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:976)
	at hudson.FilePath.deleteContents(FilePath.java:1191)
	at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1157)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:560)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:485)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, /var/jenkins_home/jobs/test_build/workspace/spec/reports/SPEC-These-are-sample-RSpec-tests.0.xml is 9 min 31 sec old

Finished: FAILURE
```
